title: Aryan Taywade
description: My portfolio site using the Midnight theme.
url: "https://kr-1234.github.io"
baseurl: "/aryantaywade.github.io"

remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-remote-theme
# Navigation bar (manual via Markdown)
# No change needed here if using plain links