title: Aryan Taywade
description: My portfolio site using the Midnight Jekyll theme.
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

url: "https://kr-1234.github.io"
baseurl: ""